import { Merriweather } from "next/font/google";
import "./globals.css";

const merry = Merriweather({ weight: '400', subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={merry.className}>{children}</body>
    </html>
  );
}
